- name: variables
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter course name
      private: false
    - name: DURATION
      prompt: please enter duration
      private: false
    - name: TRAINER
      prompt: please enter trainer name
      private: false
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration {{ DURATION }}, trainer is {{ TRAINER }}"

