- name: filters
  hosts: local
  connection: local
  tasks:
    - name: handle undefined variable
      ansible.builtin.debug:
        msg: "Hello {{ person | default('ramesh') }}"

    - name: convert string to list
      vars:
        fruits: "apple, banana, orange"  #string
      ansible.builtin.debug:
        msg: "fruits are: {{ fruits | split(',') }}"


    - name: convert map into list
      vars:
        course:
          name: "Ansible"
          duration: "10hrs"
          trainer: "sivakumar"
      ansible.builtin.debug:
        msg: "course info: {{ course | dict2items }}"

      
    - name: convert list into map
      vars:
        course:
        - {'key': 'name', 'value': 'Ansible'}
        - {'key': 'duration', 'value': '10hrs'}
        - {'key': 'trainer', 'value': 'sivakumar'}
      ansible.builtin.debug:
        msg: "course info: {{ course | items2dict }}"


    - name: convert upper to lower
      vars:
        name: "SIvaKUMAR reDDY M"
      ansible.builtin.debug:
        msg: "hello {{ name | lower}}"

    - name: convert lower to upper
      vars:
        name: "SIvaKUMAR reDDY M"
      ansible.builtin.debug:
        msg: "hello {{ name | upper}}"

    - name: print min and max
      vars:
        numbers: [12,2,34,24,3,1,65,987,34,45,23]
      ansible.builtin.debug:
        msg: "min is {{ numbers | min }} and max is {{ numbers | max }}"


    - name: check ipaddress is valid or not
      vars:
        ip: "192.168.1.1"
      ansible.builtin.debug:
        msg: "{{ ip | ansible.utils.ipaddr }}"





