172.31.11.4

[backend]
172.31.11.4
172.31.11.4
172.31.11.4

[frontend]
172.31.11.4
172.31.11.4
172.31.11.4

[expense:children]
backend
frontend

[web]
98.84.49.142 COURSE="DevOps with aws" DURATION="120hrs" TRAINER="sivakumar" ansible_user=ec2-user ansible_password=DevOps321
#localhost COURSE="ansible" DURATION="110hrs" TRAINER="sivakumar" ansible_user=ec2-user ansible_password=DevOps321

[local]
localhost

[local:vars]
#GREET="INVENTORY"
#COURSE="DevOps with aws"
#DURATION="120hrs"
#TRAINER="sivakumar"